# THE SPARKS FOUNDATIONS

# Task no. 6:- Create the Decision Tree classifier and visualize it graphically. 


# Author :- Saurabh Parab

# Importing Libraries

In [1]:
import numpy as np
import pandas as pd

# Reading the data

In [2]:
df = pd.read_csv("Iris.csv",header = 0, delimiter = ",",index_col = 0)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
# take a look at the type, number of columns, entries, null values etc..
df.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


# Checking for missing values

In [4]:
df.isnull().sum() # one way to search for null values

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

# Converting numerical variables into categorical ones

In [5]:
colname=[]
for x in df.columns:
    if df[x].dtype=='object':
        colname.append(x)
colname

['Species']

In [6]:
# For preprocessing the data
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    df[x]=le.fit_transform(df[x])

In [7]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                   
1             5.1           3.5            1.4           0.2        0
2             4.9           3.0            1.4           0.2        0
3             4.7           3.2            1.3           0.2        0
4             4.6           3.1            1.5           0.2        0
5             5.0           3.6            1.4           0.2        0

In [8]:
X=df.values[:,0:-1]
Y=df.values[:,-1]

In [9]:
Y=Y.astype(int)

# Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

X=scaler.transform(X)

# Train Test Split

In [11]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state=10)

# Implementing the Decision Tree Model

In [12]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(criterion='gini',
                                            random_state=10)

model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=10)

In [19]:
Y_pred= model_DecisionTree.predict(X_test)
print(Y_pred)

[1 2 0 1 0 1 1 1 0 1 1 2 1 0 0 2 2 0 0 0 2 2 2 0 1 0 1 1 1 2 1 1 1 2 2 0 2
 2 2 2 0 0 1 0 2]


# Evaluating the model

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm = confusion_matrix(Y_test,Y_pred)
print(cfm)

print("CLASSIFICATION MATRIX:")
print(classification_report(Y_test,Y_pred))

acc = accuracy_score(Y_test,Y_pred)
print("ACCURACY OF THE MODEL:",acc)

[[14  0  0]
 [ 0 15  2]
 [ 0  1 13]]
CLASSIFICATION MATRIX:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.88      0.91        17
           2       0.87      0.93      0.90        14

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45

ACCURACY OF THE MODEL: 0.9333333333333333


# Plotting the Tree 

In [21]:

from sklearn import tree
with open("TSF1.txt", "w") as f:
    f = tree.export_graphviz(model_DecisionTree, feature_names=df.columns[:-1],
                                            out_file=f)
   

#generate the file and upload the code in webgraphviz.com